# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='spiritbox',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x65vents.proto\x12\tspiritbox\"*\n\x0cGenericEvent\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x8f\x04\n\x08\x41ppEvent\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .spiritbox.AppEvent.AppEventType\x12*\n\x07generic\x18\x03 \x01(\x0b\x32\x17.spiritbox.GenericEventH\x00\x12\x37\n\nindication\x18\x04 \x01(\x0b\x32!.spiritbox.AppEvent.AppIndicationH\x00\x1a\xb7\x02\n\rAppIndication\x12\x41\n\x04type\x18\x01 \x01(\x0e\x32\x33.spiritbox.AppEvent.AppIndication.AppIndicationType\x12>\n\x08playlist\x18\x02 \x01(\x0b\x32*.spiritbox.AppEvent.AppIndication.PlaylistH\x00\x1a\x1d\n\rPlaylistTitle\x12\x0c\n\x04name\x18\x01 \x01(\t\x1aK\n\x08Playlist\x12?\n\x06titles\x18\x01 \x03(\x0b\x32/.spiritbox.AppEvent.AppIndication.PlaylistTitle\"0\n\x11\x41ppIndicationType\x12\x1b\n\x17\x41PP_INDICATION_PLAYLIST\x10\x00\x42\x05\n\x03ind\"+\n\x0c\x41ppEventType\x12\x0b\n\x07GENERIC\x10\x00\x12\x0e\n\nINDICATION\x10\x01\x42\x07\n\x05\x65vent\"\xd9\x02\n\x0c\x45ventMessage\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.spiritbox.EventMessage.EventType\x12\x30\n\rcontrol_event\x18\x02 \x01(\x0b\x32\x17.spiritbox.GenericEventH\x00\x12/\n\x0cplayer_event\x18\x03 \x01(\x0b\x32\x17.spiritbox.GenericEventH\x00\x12(\n\tapp_event\x18\x04 \x01(\x0b\x32\x13.spiritbox.AppEventH\x00\x12/\n\x0csource_event\x18\x05 \x01(\x0b\x32\x17.spiritbox.GenericEventH\x00\"Q\n\tEventType\x12\r\n\tAPP_EVENT\x10\x00\x12\x10\n\x0cPLAYER_EVENT\x10\x01\x12\x11\n\rCONTROL_EVENT\x10\x02\x12\x10\n\x0cSOURCE_EVENT\x10\x03\x42\x07\n\x05\x65ventb\x06proto3')
)



_APPEVENT_APPINDICATION_APPINDICATIONTYPE = _descriptor.EnumDescriptor(
  name='AppIndicationType',
  full_name='spiritbox.AppEvent.AppIndication.AppIndicationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APP_INDICATION_PLAYLIST', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=490,
  serialized_end=538,
)
_sym_db.RegisterEnumDescriptor(_APPEVENT_APPINDICATION_APPINDICATIONTYPE)

_APPEVENT_APPEVENTTYPE = _descriptor.EnumDescriptor(
  name='AppEventType',
  full_name='spiritbox.AppEvent.AppEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENERIC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDICATION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=547,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_APPEVENT_APPEVENTTYPE)

_EVENTMESSAGE_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='spiritbox.EventMessage.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APP_EVENT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_EVENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL_EVENT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOURCE_EVENT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=857,
  serialized_end=938,
)
_sym_db.RegisterEnumDescriptor(_EVENTMESSAGE_EVENTTYPE)


_GENERICEVENT = _descriptor.Descriptor(
  name='GenericEvent',
  full_name='spiritbox.GenericEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='spiritbox.GenericEvent.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='spiritbox.GenericEvent.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=69,
)


_APPEVENT_APPINDICATION_PLAYLISTTITLE = _descriptor.Descriptor(
  name='PlaylistTitle',
  full_name='spiritbox.AppEvent.AppIndication.PlaylistTitle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='spiritbox.AppEvent.AppIndication.PlaylistTitle.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=411,
)

_APPEVENT_APPINDICATION_PLAYLIST = _descriptor.Descriptor(
  name='Playlist',
  full_name='spiritbox.AppEvent.AppIndication.Playlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='titles', full_name='spiritbox.AppEvent.AppIndication.Playlist.titles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=488,
)

_APPEVENT_APPINDICATION = _descriptor.Descriptor(
  name='AppIndication',
  full_name='spiritbox.AppEvent.AppIndication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='spiritbox.AppEvent.AppIndication.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playlist', full_name='spiritbox.AppEvent.AppIndication.playlist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPEVENT_APPINDICATION_PLAYLISTTITLE, _APPEVENT_APPINDICATION_PLAYLIST, ],
  enum_types=[
    _APPEVENT_APPINDICATION_APPINDICATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ind', full_name='spiritbox.AppEvent.AppIndication.ind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=234,
  serialized_end=545,
)

_APPEVENT = _descriptor.Descriptor(
  name='AppEvent',
  full_name='spiritbox.AppEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='spiritbox.AppEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generic', full_name='spiritbox.AppEvent.generic', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indication', full_name='spiritbox.AppEvent.indication', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPEVENT_APPINDICATION, ],
  enum_types=[
    _APPEVENT_APPEVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='spiritbox.AppEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=72,
  serialized_end=599,
)


_EVENTMESSAGE = _descriptor.Descriptor(
  name='EventMessage',
  full_name='spiritbox.EventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='spiritbox.EventMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_event', full_name='spiritbox.EventMessage.control_event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_event', full_name='spiritbox.EventMessage.player_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_event', full_name='spiritbox.EventMessage.app_event', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_event', full_name='spiritbox.EventMessage.source_event', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTMESSAGE_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='spiritbox.EventMessage.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=602,
  serialized_end=947,
)

_APPEVENT_APPINDICATION_PLAYLISTTITLE.containing_type = _APPEVENT_APPINDICATION
_APPEVENT_APPINDICATION_PLAYLIST.fields_by_name['titles'].message_type = _APPEVENT_APPINDICATION_PLAYLISTTITLE
_APPEVENT_APPINDICATION_PLAYLIST.containing_type = _APPEVENT_APPINDICATION
_APPEVENT_APPINDICATION.fields_by_name['type'].enum_type = _APPEVENT_APPINDICATION_APPINDICATIONTYPE
_APPEVENT_APPINDICATION.fields_by_name['playlist'].message_type = _APPEVENT_APPINDICATION_PLAYLIST
_APPEVENT_APPINDICATION.containing_type = _APPEVENT
_APPEVENT_APPINDICATION_APPINDICATIONTYPE.containing_type = _APPEVENT_APPINDICATION
_APPEVENT_APPINDICATION.oneofs_by_name['ind'].fields.append(
  _APPEVENT_APPINDICATION.fields_by_name['playlist'])
_APPEVENT_APPINDICATION.fields_by_name['playlist'].containing_oneof = _APPEVENT_APPINDICATION.oneofs_by_name['ind']
_APPEVENT.fields_by_name['type'].enum_type = _APPEVENT_APPEVENTTYPE
_APPEVENT.fields_by_name['generic'].message_type = _GENERICEVENT
_APPEVENT.fields_by_name['indication'].message_type = _APPEVENT_APPINDICATION
_APPEVENT_APPEVENTTYPE.containing_type = _APPEVENT
_APPEVENT.oneofs_by_name['event'].fields.append(
  _APPEVENT.fields_by_name['generic'])
_APPEVENT.fields_by_name['generic'].containing_oneof = _APPEVENT.oneofs_by_name['event']
_APPEVENT.oneofs_by_name['event'].fields.append(
  _APPEVENT.fields_by_name['indication'])
_APPEVENT.fields_by_name['indication'].containing_oneof = _APPEVENT.oneofs_by_name['event']
_EVENTMESSAGE.fields_by_name['type'].enum_type = _EVENTMESSAGE_EVENTTYPE
_EVENTMESSAGE.fields_by_name['control_event'].message_type = _GENERICEVENT
_EVENTMESSAGE.fields_by_name['player_event'].message_type = _GENERICEVENT
_EVENTMESSAGE.fields_by_name['app_event'].message_type = _APPEVENT
_EVENTMESSAGE.fields_by_name['source_event'].message_type = _GENERICEVENT
_EVENTMESSAGE_EVENTTYPE.containing_type = _EVENTMESSAGE
_EVENTMESSAGE.oneofs_by_name['event'].fields.append(
  _EVENTMESSAGE.fields_by_name['control_event'])
_EVENTMESSAGE.fields_by_name['control_event'].containing_oneof = _EVENTMESSAGE.oneofs_by_name['event']
_EVENTMESSAGE.oneofs_by_name['event'].fields.append(
  _EVENTMESSAGE.fields_by_name['player_event'])
_EVENTMESSAGE.fields_by_name['player_event'].containing_oneof = _EVENTMESSAGE.oneofs_by_name['event']
_EVENTMESSAGE.oneofs_by_name['event'].fields.append(
  _EVENTMESSAGE.fields_by_name['app_event'])
_EVENTMESSAGE.fields_by_name['app_event'].containing_oneof = _EVENTMESSAGE.oneofs_by_name['event']
_EVENTMESSAGE.oneofs_by_name['event'].fields.append(
  _EVENTMESSAGE.fields_by_name['source_event'])
_EVENTMESSAGE.fields_by_name['source_event'].containing_oneof = _EVENTMESSAGE.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['GenericEvent'] = _GENERICEVENT
DESCRIPTOR.message_types_by_name['AppEvent'] = _APPEVENT
DESCRIPTOR.message_types_by_name['EventMessage'] = _EVENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericEvent = _reflection.GeneratedProtocolMessageType('GenericEvent', (_message.Message,), dict(
  DESCRIPTOR = _GENERICEVENT,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:spiritbox.GenericEvent)
  ))
_sym_db.RegisterMessage(GenericEvent)

AppEvent = _reflection.GeneratedProtocolMessageType('AppEvent', (_message.Message,), dict(

  AppIndication = _reflection.GeneratedProtocolMessageType('AppIndication', (_message.Message,), dict(

    PlaylistTitle = _reflection.GeneratedProtocolMessageType('PlaylistTitle', (_message.Message,), dict(
      DESCRIPTOR = _APPEVENT_APPINDICATION_PLAYLISTTITLE,
      __module__ = 'events_pb2'
      # @@protoc_insertion_point(class_scope:spiritbox.AppEvent.AppIndication.PlaylistTitle)
      ))
    ,

    Playlist = _reflection.GeneratedProtocolMessageType('Playlist', (_message.Message,), dict(
      DESCRIPTOR = _APPEVENT_APPINDICATION_PLAYLIST,
      __module__ = 'events_pb2'
      # @@protoc_insertion_point(class_scope:spiritbox.AppEvent.AppIndication.Playlist)
      ))
    ,
    DESCRIPTOR = _APPEVENT_APPINDICATION,
    __module__ = 'events_pb2'
    # @@protoc_insertion_point(class_scope:spiritbox.AppEvent.AppIndication)
    ))
  ,
  DESCRIPTOR = _APPEVENT,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:spiritbox.AppEvent)
  ))
_sym_db.RegisterMessage(AppEvent)
_sym_db.RegisterMessage(AppEvent.AppIndication)
_sym_db.RegisterMessage(AppEvent.AppIndication.PlaylistTitle)
_sym_db.RegisterMessage(AppEvent.AppIndication.Playlist)

EventMessage = _reflection.GeneratedProtocolMessageType('EventMessage', (_message.Message,), dict(
  DESCRIPTOR = _EVENTMESSAGE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:spiritbox.EventMessage)
  ))
_sym_db.RegisterMessage(EventMessage)


# @@protoc_insertion_point(module_scope)
